ROLE_USER = "USER"
ROLE_TECHNICIAN = "TECHNICIAN"
ROLE_REVIEWER = "REVIEWER"
ROLE_ADMIN = "ADMIN"

VALID_USER_ROLES = {ROLE_USER, ROLE_TECHNICIAN, ROLE_REVIEWER, ROLE_ADMIN}
LLM_EXECUTION_ROLES = {ROLE_TECHNICIAN, ROLE_ADMIN}
HUMAN_REVIEW_ROLES = {ROLE_REVIEWER, ROLE_ADMIN}
